name: flutter_custom_laravel_api_authentication
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.2.0
  get_it: ^9.1.1
  go_router: ^17.0.0
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  sentry_flutter: ^9.8.0
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Assets
  assets:
    - .env